- app/controllers/events_controller.rb
- app/views/events/index.html.erb
Add index method of events controller + Start a basic view of index (events controller)
> Add Index method of Events Controller + Add basic view to events#index

- app/views/shared/_navbar.html.erb
j'ai ajouté un template de navbar à compléter depuis les sources de UI KITT
> add vierge navbar from ui-kitt lewagon

- app/controllers/bookings_controller.rb
- app/views/bookings/index.html.erb
booking view et controller def index booking
> booking-view

- app/views/events/show.html.erb
J'ai réarrangé le code html.
J'ai lis des div globales : .wrapper (que je vais faire là dans css), 
.head-summary: avec dedans la date, le titre et l'organisateur, 
.global: qui a deux parties main (img et détails) et side (re date et localisation)
> Rearranged html code of the show

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_wrapper.scss
> added wrapper class + its css

- .gitignore
- Gemfile
- Gemfile.lock
- app/models/event.rb
- app/models/user.rb
- app/views/events/show.html.erb
- config/environments/development.rb
- config/storage.yml
- db/migrate/20200818093923_create_active_storage_tables.active_storage.rb
- db/schema.rb
- db/seeds.rb
> Adding cloudinary

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_cards-category.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_index.scss
- app/views/events/index.html.erb
> Change cards css

- app/views/events/index.html.erb
> add btn add event to home page

- .gitignore
- app/assets/stylesheets/components/_navbar.scss
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/shared/_navbar.html.erb
Cloudinary OK
Navbar bottom Ok
Link Logo top left Ok
Profil avatar : Links vers Mes Réservations Ok
> Add cloudinary florian

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_small-wrappers.scss
- app/views/events/show.html.erb
j'ai modifié le haut de la page avec le titre de la show
> front head page

- .gitignore
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/config/_fonts.scss
- app/views/bookings/index.html.erb
> font-changed

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_button.scss
small change to erase the default decoration of links
> links on button with no decoration

- app/views/shared/_navbar.html.erb
Ajout des 2 avatar depuis cloudinary
Ajout d'un bouton "Se déconnecter" permettant de switcher entre Michel et Julie
> ajout des 2 avatars et du bouton se déconnecter

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_index.scss
- app/controllers/events_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_mapbox.js
- app/models/event.rb
- app/views/events/show.html.erb
- config/initializers/geocoder.rb
- db/migrate/20200819084310_add_coordinates_to_events.rb
- db/schema.rb
- db/seeds.rb
- package.json
- yarn.lock
> unfinished map

- app/views/events/index.html.erb
Add a search field in banner. Must be changed after.
> add search field to banner

- app/assets/stylesheets/components/_banner.scss
> change banner height

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_small-wrappers.scss
- app/assets/stylesheets/components/_text.scss
- app/views/events/index.html.erb
cards style without the link on the whole card
> index cards style added

- app/controllers/events_controller.rb
- app/javascript/plugins/init_mapbox.js
- app/views/events/show.html.erb
- app/views/layouts/application.html.erb
- config/initializers/geocoder.rb
> pink marker on map

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_icons.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_small-wrappers.scss
- app/assets/stylesheets/components/_text.scss
- app/assets/stylesheets/components/_wrapper.scss
- app/controllers/bookings_controller.rb
- app/views/bookings/index.html.erb
- app/views/events/show.html.erb
- app/views/shared/_footer.html.erb
- config/routes.rb
- destroy button on bookings
- footer stays at the bottom of the page
- placeholder in "my bookings" when no bookings yet
- map in show larger and white bottom border suppressed
> Suppress bookings

- app/controllers/events_controller.rb
- config/routes.rb
J'ai ajouté : 
- la route my_events
- les méthodes dans le controller events (pas sûr que ça marche pour my_events)
-les fichiers pour les views incluant un "_form.html.erb" pour faire une partial de nex et edit
> organizer route, controller and views

- app/controllers/events_controller.rb
- app/views/events/index.html.erb
Add 2 search fields (event title and location)
Increase fields size
> Add 2 search fields to bbanner + Change fields to be larger

- app/assets/stylesheets/components/_card.scss
- db/seeds.rb
J'ai changé la photo sur les cartes comme Manu nous l'avait indiqué. 
Et dans la seed j'ai mis toutes les adresses et titres sur une ligne.
> changed some front
